import { Router, type IRouter } from "express";
import healthRouter      from "./health";
import authRouter        from "./auth";
import assetsRouter      from "./assets";
import jobsRouter        from "./jobs";
import photosRouter      from "./photos";
import teamsRouter       from "./teams";
import auditsRouter      from "./audits";
import auditQuotaRouter  from "./audit-quota";
import programmesRouter  from "./programmes";
import dashboardRouter   from "./dashboard";
import scheduleRouter    from "./schedule";
import auditLogRouter    from "./audit-log";
import usersRouter       from "./users";
import teamRouter        from "./team";
import settingsRouter    from "./settings";
import reportsRouter     from "./reports";
import adminPatchesRouter from "./admin-patches";
import plantPaletteRouter from "./plant-palette";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(assetsRouter);
router.use(jobsRouter);
router.use(photosRouter);
router.use(teamsRouter);
router.use(auditQuotaRouter);
router.use(auditsRouter);
router.use(programmesRouter);
router.use(dashboardRouter);
router.use(scheduleRouter);
router.use(auditLogRouter);
router.use(usersRouter);
router.use(teamRouter);
router.use(settingsRouter);
router.use(reportsRouter);
router.use("/admin", adminPatchesRouter);
router.use(plantPaletteRouter);

export default router;
