// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/garden-app/AssetList.tsx": () => import("../components/mockups/garden-app/AssetList.tsx"),
  "./components/mockups/garden-app/Dashboard.tsx": () => import("../components/mockups/garden-app/Dashboard.tsx"),
  "./components/mockups/garden-app/DataCollectionForm.tsx": () => import("../components/mockups/garden-app/DataCollectionForm.tsx"),
  "./components/mockups/garden-app/InfillPlanting.tsx": () => import("../components/mockups/garden-app/InfillPlanting.tsx"),
  "./components/mockups/garden-app/InternalAudits.tsx": () => import("../components/mockups/garden-app/InternalAudits.tsx"),
  "./components/mockups/garden-app/JobCheckout.tsx": () => import("../components/mockups/garden-app/JobCheckout.tsx"),
  "./components/mockups/garden-app/JobDetail.tsx": () => import("../components/mockups/garden-app/JobDetail.tsx"),
  "./components/mockups/garden-app/JobList.tsx": () => import("../components/mockups/garden-app/JobList.tsx"),
  "./components/mockups/garden-app/Login.tsx": () => import("../components/mockups/garden-app/Login.tsx"),
  "./components/mockups/garden-app/MaintenanceScheduler.tsx": () => import("../components/mockups/garden-app/MaintenanceScheduler.tsx"),
  "./components/mockups/garden-app/RoleMatrix.tsx": () => import("../components/mockups/garden-app/RoleMatrix.tsx"),
  "./components/mockups/garden-app/Specification.tsx": () => import("../components/mockups/garden-app/Specification.tsx")
};
