// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/field-ops/UpNextGeosequence.tsx": () => import("../components/mockups/field-ops/UpNextGeosequence.tsx"),
  "./components/mockups/garden-app/AssetDetailRedesign.tsx": () => import("../components/mockups/garden-app/AssetDetailRedesign.tsx"),
  "./components/mockups/garden-app/AssetDetailView.tsx": () => import("../components/mockups/garden-app/AssetDetailView.tsx"),
  "./components/mockups/garden-app/AssetList.tsx": () => import("../components/mockups/garden-app/AssetList.tsx"),
  "./components/mockups/garden-app/AssetMap.tsx": () => import("../components/mockups/garden-app/AssetMap.tsx"),
  "./components/mockups/garden-app/Dashboard.tsx": () => import("../components/mockups/garden-app/Dashboard.tsx"),
  "./components/mockups/garden-app/DataCollectionForm.tsx": () => import("../components/mockups/garden-app/DataCollectionForm.tsx"),
  "./components/mockups/garden-app/InfillPlanting.tsx": () => import("../components/mockups/garden-app/InfillPlanting.tsx"),
  "./components/mockups/garden-app/InternalAudits.tsx": () => import("../components/mockups/garden-app/InternalAudits.tsx"),
  "./components/mockups/garden-app/JobCheckout.tsx": () => import("../components/mockups/garden-app/JobCheckout.tsx"),
  "./components/mockups/garden-app/JobDetail.tsx": () => import("../components/mockups/garden-app/JobDetail.tsx"),
  "./components/mockups/garden-app/JobList.tsx": () => import("../components/mockups/garden-app/JobList.tsx"),
  "./components/mockups/garden-app/Login.tsx": () => import("../components/mockups/garden-app/Login.tsx"),
  "./components/mockups/garden-app/MaintenanceScheduler.tsx": () => import("../components/mockups/garden-app/MaintenanceScheduler.tsx"),
  "./components/mockups/garden-app/MulchingProgramme.tsx": () => import("../components/mockups/garden-app/MulchingProgramme.tsx"),
  "./components/mockups/garden-app/ReactiveJobFlow.tsx": () => import("../components/mockups/garden-app/ReactiveJobFlow.tsx"),
  "./components/mockups/garden-app/Reports.tsx": () => import("../components/mockups/garden-app/Reports.tsx"),
  "./components/mockups/garden-app/RoleMatrix.tsx": () => import("../components/mockups/garden-app/RoleMatrix.tsx"),
  "./components/mockups/garden-app/Specification.tsx": () => import("../components/mockups/garden-app/Specification.tsx"),
  "./components/mockups/schedule-header/VariantA.tsx": () => import("../components/mockups/schedule-header/VariantA.tsx"),
  "./components/mockups/schedule-header/VariantB.tsx": () => import("../components/mockups/schedule-header/VariantB.tsx"),
  "./components/mockups/schedule-header/VariantC.tsx": () => import("../components/mockups/schedule-header/VariantC.tsx"),
  "./components/mockups/day-view-options/RouteList.tsx": () => import("../components/mockups/day-view-options/RouteList.tsx"),
  "./components/mockups/day-view-options/TimelineCards.tsx": () => import("../components/mockups/day-view-options/TimelineCards.tsx")
};
