// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/garden-app/AssetList.tsx": () => import("../components/mockups/garden-app/AssetList.tsx"),
  "./components/mockups/garden-app/Dashboard.tsx": () => import("../components/mockups/garden-app/Dashboard.tsx"),
  "./components/mockups/garden-app/DataCollectionForm.tsx": () => import("../components/mockups/garden-app/DataCollectionForm.tsx"),
  "./components/mockups/garden-app/MaintenanceScheduler.tsx": () => import("../components/mockups/garden-app/MaintenanceScheduler.tsx")
};
